Models/CreditCalcMainItem.cs
using System.Xml.Linq;

namespace CredicCalc.Models
{
    public class CreditCalcItem
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public double PaymentSum { get; set; }
        public double MainDebt { get; set; }
            
        public double Percent { get; set; }
        public double RemainingDebt { get; set; }


        public string DateStr 
        {
            get { return this.Date.ToString("dd.MM.yyyy"); }
        }

        public string PaymentSumStr
        {
            get { return String.Format("{0:0.00}", this.PaymentSum); }
        }

        public string MainDebtStr
        {
            get { return String.Format("{0:0.00}", this.MainDebt); }
        }

        public string PercentStr
        {
            get { return String.Format("{0:0.00}", this.Percent); }
        }

        public string RemainingDebtStr
        {
            get { return String.Format("{0:0.00}", this.RemainingDebt); }
        }

    }
}

Models/ErrorViewModel.cs
namespace CredicCalc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CreditCalcAdditionalController.cs
using CredicCalc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;


namespace CredicCalc.Controllers
{
    public class CreditCalcAdditionalController : Controller
    {
        private readonly ILogger<CreditCalcAdditionalController> _logger;

        public CreditCalcAdditionalController(ILogger<CreditCalcAdditionalController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            CreditCalcAdditionalParam param = new CreditCalcAdditionalParam();
            param.LoanSum = 60000;
            param.LoanTermDay = 10;
            param.LoanRateDay = 10;
            param.StepDay = 1;
            return View(param);
        
        }

        public IActionResult Results(CreditCalcAdditionalParam? creditCalcAdditionalParam)
        {
            if (Request.Method == "GET")
            {
                return RedirectToAction("Index");
            }
            List<CreditCalcItem> items = new List<CreditCalcItem>();
            double sum = creditCalcAdditionalParam.LoanSum;
            double rate = creditCalcAdditionalParam.LoanRateDay;
            double stepRate = rate / 100 * creditCalcAdditionalParam.StepDay;
            double numOfSteps = creditCalcAdditionalParam.LoanTermDay / creditCalcAdditionalParam.StepDay;


            double stepPayment = sum * (stepRate + (stepRate / ((Math.Pow(1 + stepRate, numOfSteps)) - 1)));
            DateTime now = DateTime.Now;
            double overpayment = 0;
            int counter = 1;
            for (int j = 0; j < creditCalcAdditionalParam.LoanTermDay; j+=creditCalcAdditionalParam.StepDay)
            {
                if (sum <= 0.0001) break;
                CreditCalcItem item = new CreditCalcItem();
                item.Id = counter;
                item.Date = now.AddDays(creditCalcAdditionalParam.StepDay *(counter));
                item.PaymentSum = stepPayment;
                item.Percent = sum * stepRate;
                item.MainDebt = stepPayment - item.Percent;
                item.RemainingDebt = sum - item.MainDebt;
                overpayment = overpayment + sum * stepRate;
                sum = sum - (stepPayment - (sum * stepRate));
                counter++;
                items.Add(item);
            }
            items.Last().RemainingDebt = 0;
            ViewBag.Param = creditCalcAdditionalParam;
            ViewBag.LastDate = items.Last().Date.ToString("dd.MM.yyyy");
            ViewBag.Payment = String.Format("{0:0.00}", stepPayment);
            ViewBag.Overpayment = String.Format("{0:0.00}", overpayment);
            ViewBag.FullSum = String.Format("{0:0.00}", overpayment + creditCalcAdditionalParam.LoanSum);
            return View(items);
        }

        [AcceptVerbs("Get", "Post")]
        public IActionResult CheckRate(double LoanRateDay)
        {
            return Json(LoanRateDay >= 0.01);
        }

        [AcceptVerbs("Get", "Post")]
        public IActionResult CheckTerm(int LoanTermDay, int StepDay )
        {

            if (LoanTermDay < StepDay)
            {
                return Json("Срок займа должен быть не меньше шага платежа");
            }
             if (LoanTermDay % StepDay != 0) 
            {
                return Json("Срок займа должен быть кратен шагу платежа");
            }

            return Json(true);
        }

     

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/CreditCalcMainController.cs
using CredicCalc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Web.Helpers;



namespace CredicCalc.Controllers
{
    public class CreditCalcMainController : Controller
    {
        private readonly ILogger<CreditCalcMainController> _logger;

        public CreditCalcMainController(ILogger<CreditCalcMainController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            CreditCalcMainParam param = new CreditCalcMainParam();
            param.LoanTermMonth = 6;
            param.LoanSum = 100000;
            param.LoanRateYear = 10;
            return View(param);
        }

       // [HttpPost]
        public IActionResult Results(CreditCalcMainParam creditCalcMainParam)
        {

            
            if (Request.Method == "GET") 
            {
                return RedirectToAction("Index");
            }

            List<CreditCalcItem> items = new List<CreditCalcItem>();
            double sum = creditCalcMainParam.LoanSum;
            double rate = creditCalcMainParam.LoanRateYear;
            double monthRate = rate / 100 / 12;

            double monthPayment = sum * (monthRate + (monthRate / ((Math.Pow(1+ monthRate, creditCalcMainParam.LoanTermMonth))-1)));
            DateTime now = DateTime.Now;
            double overpayment = 0;
            for (int j = 0; j < creditCalcMainParam.LoanTermMonth; j++) 
            {
                CreditCalcItem item = new CreditCalcItem();
                item.Id = j + 1;
                item.Date = now.AddMonths(j+1);
                item.PaymentSum =monthPayment;
                item.Percent =  sum * monthRate;
                item.MainDebt = monthPayment - item.Percent;
                item.RemainingDebt = sum - item.MainDebt;
                overpayment = overpayment + sum * monthRate;
                sum = sum - (monthPayment - (sum * monthRate));
             
                items.Add(item);
            }
            items.Last().RemainingDebt = 0;
            ViewBag.Param = creditCalcMainParam;
            ViewBag.LastDate = items.Last().Date.ToString("dd.MM.yyyy");
            ViewBag.Payment = String.Format("{0:0.00}", monthPayment);
            ViewBag.Overpayment = String.Format("{0:0.00}", overpayment);
            ViewBag.FullSum = String.Format("{0:0.00}", overpayment + creditCalcMainParam.LoanSum);

            return View( items);
        }

        [AcceptVerbs("Get", "Post")]
        public IActionResult CheckRate(double LoanRateYear)
        {
          return Json(LoanRateYear >=0.01);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using CredicCalc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CredicCalc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/CreditCalcAdditional/Index.cshtml
@model CredicCalc.Models.CreditCalcAdditionalParam
@{

    ViewData["Title"] = "Дополнительный";

}
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}


<h1 class="display-4">Аннуитетный калькулятор (дополнительный)</h1>

@using (Html.BeginForm("Results", "CreditCalcAdditional", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{

    <div class="row">
        <div class="col">
            <label class="form-label">Сумма займа</label>
           
            <br>
            @Html.TextBoxFor(m => m.LoanSum, new { @class = "form-control", type = "number", oninput="changeValue(this)"})
            @Html.TextBoxFor(m => m.LoanSum, new {@class = "form-range",  type = "range" , min="5000", max="30000000", oninput="changeValue(this)"})
        </div>
        <div class="col">
            <br>
            @Html.ValidationMessageFor(m => m.LoanSum)
        </div>
    </div>



    <div class="row">
        <div class="col">


            <label class="form-label">Ставка (в день)</label>
            <br>
            @Html.TextBoxFor(m => m.LoanRateDay, new { @class = "form-control", type = "number", oninput="changeValue(this)"})
            @Html.TextBoxFor(m => m.LoanRateDay, new { @class = "form-range",  type = "range" , min="0.01", max="200", step="0.01",  oninput="changeValue(this)" })


        </div>
        <div class="col">
            <br>
            @Html.ValidationMessageFor(m => m.LoanRateDay)
        </div>
    </div>

    <div class="row">
        <div class="col">


            <label class="form-label">Шаг платежа (в днях)</label>
            <br>
            @Html.TextBoxFor(m => m.StepDay, new { @class = "form-control", type = "number", oninput="changeValue(this)"})
            @Html.TextBoxFor(m => m.StepDay, new { @class = "form-range",  type = "range" , min="1", max="300",  oninput="changeValue(this)" })


        </div>
        <div class="col">
            <br>
            @Html.ValidationMessageFor(m => m.StepDay)
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label class="form-label">Срок займа (в днях)</label>
            <br>
            @Html.TextBoxFor(m => m.LoanTermDay, new { @class = "form-control", type = "number", oninput="changeValue(this)"})
            @Html.TextBoxFor(m => m.LoanTermDay, new { @class = "form-range",  type = "range" , min="1", max="200000", oninput="changeValue(this)" })


        </div>
        <div class="col">
            <br>
            @Html.ValidationMessageFor(m => m.LoanTermDay)
            <div id="LoanTermValidation"></div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">Рассчитать</button>
        </div>
    </div>
}
<script>

    document.addEventListener("DOMContentLoaded", ready);
    function ready() {
       

        $('span[data-valmsg-for="LoanTermDay"]').on("DOMSubtreeModified", function () {
            let stepday = $('input[name="StepDay"]').val();
            let loanTermDay = $('input[name="LoanTermDay"]').val();
           
            if ((loanTermDay % stepday) !==0 && $('span[data-valmsg-for="LoanTermDay"]').hasClass("field-validation-error") ) {

             
                let periodsnumDown = Math.floor(loanTermDay / stepday)
                let periodsnumUp = Math.ceil(loanTermDay / stepday)

            
                
                if (periodsnumDown == 0)
                {
                    $('#LoanTermValidation').html("Изменить на " + createButton(stepday * periodsnumUp));
                }
                else
                {
                    $('#LoanTermValidation').html("Изменить на " + createButton(stepday * periodsnumDown) + ' или ' + createButton(stepday * periodsnumUp));
                }
                

         }
         else
         {
        $('#LoanTermValidation').html("");
         }
        });

    }
    function createButton(value)
    {
        return " <span class='btn btn-success' onclick='setLoanTermValue(" + value + ")'> " + value + "</span>";
    }

    function setLoanTermValue(value)
    {
        $('input[name="LoanTermDay"]').each(function (i, obj) {
            // alert(obj.id);
            obj.value = value;
        });
    }
   
    function changeValue(el) {

        $('input[name="' + el.id + '"]').each(function (i, obj) {
            // alert(obj.id);
            obj.value = el.value;
        });
    }
</script>

Views/CreditCalcAdditional/Results.cshtml
@model List<CreditCalcItem>
@{
    ViewData["Title"] = "Дополнительный";
}

<div class="text-center">
    <h1 class="display-4"> Результаты расчета</h1>


    <table class="table">
        <thead>
            <tr>
                <th>Дата</th>
                <th>Сумма займа</th>
                <th>Ставка</th>
                <th>Срок</th>
                <th>Шаг</th>
                
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@DateTime.Now.ToString("dd.MM.yyyy")</td>
                <td>@ViewBag.Param.LoanSum</td>
                <td>@ViewBag.Param.LoanRateDay</td>
                <td>@ViewBag.Param.LoanTermDay</td>
                <td>@ViewBag.Param.StepDay</td>
            </tr>
        </tbody>
    </table>



    <table class="table table-bordered">
        <thead>
        <tr>
            <th>№</th>
            <th>Дата</th>
            <th>Сумма платежа</th>
            <th>Основной долг</th>
            <th>Проценты</th>
            <th>Остаток</th>
        </tr>
        </thead>
        <tbody>
            @foreach (CreditCalcItem item in Model)
    {

        <tr>
            <td>@item.Id</td>
            <td>@item.DateStr</td>
            <td>@item.PaymentSumStr</td>
            <td>@item.MainDebtStr</td>
            <td>@item.PercentStr</td>
           <td>@item.RemainingDebtStr</td>
        </tr>
    }

            </tbody>
         </table>

    <table class="table">
        <thead>
            <tr>
                <th>Платеж</th>
                <th>Переплата по процентам</th>
                <th>Дата последнего платежа</th>
                <th>Общая стоимость кредита</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@ViewBag.Payment</td>
                <td>@ViewBag.Overpayment</td>
                <td>@ViewBag.lastDate</td>
                <td>@ViewBag.FullSum</td>



            </tr>
        </tbody>
    </table>
        
</div>

Views/CreditCalcMain/Index.cshtml
@model CredicCalc.Models.CreditCalcMainParam
@{
  
    ViewData["Title"] = "Основной";

}
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}


    <h1 class="display-4">Аннуитетный калькулятор</h1>
    
    @using (Html.BeginForm("Results", "CreditCalcMain", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {

    <div class="row">
        <div class="col">
            @Html.LabelFor(m=>m.LoanSum, "Сумма займа", new { @class = "form-label"})

            @Html.TextBoxFor(m => m.LoanSum, new { @class = "form-control",  type = "number"})
        </div>
        <div class="col">
            <br>
            @Html.ValidationMessageFor(m => m.LoanSum)
        </div>
    </div>
    <div class="row">
        <div class="col">
            @Html.LabelFor(m=>m.LoanTermMonth, "Срок займа (в месяцах)", new { @class = "form-label"})
            @Html.TextBoxFor(m => m.LoanTermMonth, new { @class = "form-control",  type = "number" })

        </div>
        <div class="col">
            <br>
            @Html.ValidationMessageFor(m => m.LoanTermMonth)
        </div>
    </div>


    <div class="row">
        <div class="col">
            @Html.LabelFor(m=>m.LoanRateYear, "Ставка (в год)", new { @class = "form-label"})
            @Html.TextBoxFor(m => m.LoanRateYear, new { @class = "form-control", type = "number" , step="0.01"})

        </div>
        <div class="col">
            <br>
            @Html.ValidationMessageFor(m => m.LoanRateYear)
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">Рассчитать</button>
    </div>
       </div>
    }

Views/CreditCalcMain/Results.cshtml
@model List<CreditCalcItem>
@{
    ViewData["Title"] = "Основной";
}

<div class="text-center">
    <h1 class="display-4"> Результаты расчета</h1>
     <table class="table">
        <thead>
            <tr>
                <th>Дата</th>
                <th>Сумма займа</th>
                <th>Ставка</th>
                <th>Срок</th>
                <th></th>
                
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@DateTime.Now.ToString("dd.MM.yyyy")</td></td>
                <td>@ViewBag.Param.LoanSum</td>
                <td>@ViewBag.Param.LoanRateYear</td>
                <td>@ViewBag.Param.LoanTermMonth</td>
                <td></td>
            </tr>
        </tbody>
    </table>
        <table class="table table-bordered">
        <thead>
        <tr>
            <th>№</th>
            <th>Дата</th>
            <th>Сумма платежа</th>
            <th>Основной долг</th>
            <th>Проценты</th>
            <th>Остаток</th>
        </tr>
        </thead>
        <tbody>
            @foreach (CreditCalcItem item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.DateStr</td>
            <td>@item.PaymentSumStr</td>
            <td>@item.MainDebtStr</td>
            <td>@item.PercentStr</td>
           <td>@item.RemainingDebtStr</td>
        </tr>
    }
            </tbody>
         </table>

    <table class="table">
        <thead>
            <tr>
                <th>Ежемесячный платеж</th>
                <th>Переплата по процентам</th>
                <th>Дата последнего платежа</th>
                <th>Общая стоимость кредита</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@ViewBag.Payment</td>
                <td>@ViewBag.Overpayment</td>
                <td>@ViewBag.lastDate</td>
                <td>@ViewBag.FullSum</td>
            </tr>
        </tbody>
    </table>
        
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Главная";
}

<div class="text-center">
    <h1 class="display-4">Главная</h1>
    <h3> Реализация простого кредитного калькулятора для расчета аннуитетных займов в виде веб-приложения</h3>
    <h3>
        Стек:
        C# ASP.NET Core MVC + Bootstrap + jQuery.
    </h3>   
    <h4>
        Алгоритм расчета аннуитетных займов из:
        <a  href=" http://www.platesh.ru/annuitetnie-plateshi/" class="link-primary">www.platesh.ru</a>
     </h4>
    <h4>
       Кредитный калькулятор для проверки:
        <a href=" https://calculator888.ru/kreditnyy-kalkulyator" class="link-primary">калькулятор</a>

    </h4>

    <hr>

    <h4>
        Реализация калькулятора 
    </h4>
    <h4>
       
        <a href="/CreditCalcMain" class="link-primary">Основное задание</a>
        <a href="/CreditCalcAdditional" class="link-primary">Дополнительное задание</a>



    </h4>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Кредитный калькулятор</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CredicCalc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Кредитный калькулятор</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CreditCalcMain" asp-action="Index">Основной</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CreditCalcAdditional" asp-action="Index">Дополнительный</a>
                        </li>    
                        <li class="nav-item">
                            <a class="nav-link text-dark"   href=" https://calculator888.ru/kreditnyy-kalkulyator" class="link-primary">Сторонний кредитный калькулятор</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
@*        <div class="container">
            &copy; 2023 - CredicCalc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>*@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>